import{S as v,i as l,a as x}from"./assets/vendor-b52d9f5e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const u=document.querySelector(".search-form"),d=document.querySelector(".gallery"),i=document.querySelector(".next-btn");let c=0,m="";const f=new v(".gallery a",{captionsData:"alt",captionDelay:250});u.addEventListener("submit",C);i.addEventListener("click",b);async function C(t){t.preventDefault();const o=u.elements.query.value;if(m=o,c=1,i.classList.add("is-hidden"),d.innerHTML="",!o.trim()){l.show({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}k();try{const r=await y(m,c);if(r.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}),u.reset();return}d.innerHTML=g(r.hits),f.refresh(),r.hits.length>=40?i.classList.remove("is-hidden"):l.show({title:"❕",theme:"dark",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageColor:"white",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3}),p(),u.reset()}catch(r){L(r)}finally{w()}}async function y(t,o){const r="https://pixabay.com/api/",a="41927866-cfb01af7ede59fae11104cea9";return(await x.get(r,{params:{key:a,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}})).data}function g(t){return t.map(({comments:o,downloads:r,largeImageURL:a,likes:e,webformatURL:s,tags:n,views:S})=>`<li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${s}" alt="${n}">
            <ul class="gallery-item-description">
              <li>Likes: ${e}</li>
              <li>Views: ${S}</li>
              <li>Downloads: ${r}</li>
              <li>Comments: ${o}</li>
            </ul>
          </a>
        </li>`).join("")}function L(t){console.error(t),d.innerHTML="",l.show({theme:"dark",message:t.stack,messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}),i.removeEventListener("click",b),i.classList.add("is-hidden")}async function b(){h.classList.remove("is-hidden"),i.classList.add("is-hidden"),c+=1,k();try{const t=await y(m,c);if(c*40>=t.totalHits){if(l.show({title:"❕",theme:"dark",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageColor:"white",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3}),t.hits.length>0){d.insertAdjacentHTML("beforeend",g(t.hits)),f.refresh(),i.classList.add("is-hidden"),p();return}}else d.insertAdjacentHTML("beforeend",g(t.hits)),f.refresh(),p(),i.classList.remove("is-hidden")}catch(t){L(t)}finally{w(),h.classList.add("is-hidden")}}const h=document.querySelector(".loader");function w(){setTimeout(()=>{h.style.display="none"},500)}function k(){h.style.display="block"}function p(){window.scrollBy({top:640,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
