import{S as v,i as l,a as x}from"./assets/vendor-b52d9f5e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const n of i.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerpolicy&&(i.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?i.credentials="include":e.crossorigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function o(e){if(e.ep)return;e.ep=!0;const i=a(e);fetch(e.href,i)}})();const m=document.querySelector(".search-form"),d=document.querySelector(".gallery"),r=document.querySelector(".next-btn"),h=document.querySelector(".loader");let c=0,u="";const f=new v(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",C);r.addEventListener("click",b);async function C(s){if(s.preventDefault(),u=s.currentTarget.elements.query.value.trim(),c=1,k(),r.classList.add("is-hidden"),d.innerHTML="",!u){l.show({title:"❕",theme:"light",message:"Please, fill in the search field",messageSize:"20px",messageColor:"#808080",backgroundColor:"#e7fc44",position:"topLeft",timeout:3e3});return}try{const t=await y(u,c);if(t.hits.length===0){l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}),m.reset();return}d.insertAdjacentHTML("beforeend",p(t.hits)),f.refresh(),t.hits.length>=40?r.classList.remove("is-hidden"):l.show({title:"❕",theme:"dark",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageColor:"white",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3}),m.reset()}catch(t){L(t)}finally{w()}}async function y(s,t){const a="https://pixabay.com/api/",o="41927866-cfb01af7ede59fae11104cea9";return(await x.get(a,{params:{key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}})).data}function p(s){return s.map(({comments:t,downloads:a,largeImageURL:o,likes:e,webformatURL:i,tags:n,views:S})=>`<li class="gallery-item">
        <a class="gallery-link" href="${o}">
            <img class="gallery-image" src="${i}" alt="${n}">
            <ul class="gallery-description">
              <li class="gallery-description-item">Likes: <span class="discrp-item">${e}</span> </li>
              <li class="gallery-description-item">Views: <span class="discrp-item">${S}</span></li>
              <li class="gallery-description-item">Downloads: <span class="discrp-item">${a}</span></li>
              <li class="gallery-description-item">Comments: <span class="discrp-item">${t}</span></li>
            </ul>
        </a>
    </li>`).join("")}function L(s){console.error(s),d.innerHTML="",l.show({theme:"dark",message:s.stack,messageSize:"16px",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",timeout:5e3}),r.removeEventListener("click",b),r.classList.add("is-hidden")}async function b(){h.classList.remove("is-hidden"),r.classList.add("is-hidden"),c+=1,k();try{const s=await y(u,c);if(c*40>=s.totalHits){if(l.show({title:"❕",theme:"dark",message:"We're sorry, but you've reached the end of search results.",messageSize:"16px",messageColor:"white",backgroundColor:"#4e75ff",position:"topRight",timeout:5e3}),s.hits.length>0){d.insertAdjacentHTML("beforeend",p(s.hits)),f.refresh(),r.classList.add("is-hidden"),g();return}}else d.insertAdjacentHTML("beforeend",p(s.hits)),f.refresh(),g(),r.classList.remove("is-hidden")}catch(s){L(s)}finally{w(),h.classList.add("is-hidden")}}function w(){setTimeout(()=>{h.style.display="none"},500)}function k(){h.style.display="block"}function g(){window.scrollBy({top:640,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
